### ISSUE TITLE
[Commit] Merge 기능구현

### ISSUE THREAD

**Issue by gwanwoo96** [codestates/story-hub-client#141]
### ISSUE
- Group:  `client`
- Type:  `feature`
- Detail: 
0. Commit 이 삭제되는 경우는 오로지 해당 commit을 작성한 사람과 원작자만 삭제할 수 있다. // 머지된 것은 삭제불가함
 (Content 수정은 원작자 상시가능 // 커밋은 머지되면 수정불가능)
1. Detail Content Page에선 원작자가 머지한 commit만 content로써 렌더된다.
 => 누가 어디까지 작성했는지는 따로 보여주지 않는다. // prototype과는 달라짐
2. Detail Commit Page에서 머지된 commit은 최상위에 위치하고 머지되지 않았던 commit도 depth 별로 렌더해준다.(prototype)

### TODO
1. [ ] Commit 이 삭제되는 경우는 오로지 해당 commit을 작성한 사람과 원작자만 삭제할 수 있다. // 머지된 것은 삭제불가함
2. [ ] Detail Content Page에선 원작자가 머지한 commit만 content로써 렌더된다.
3. [ ] Detail Commit Page에서 머지된 commit은 최상위에 위치하고 머지되지 않았던 commit도 depth 별로 렌더해준다.(prototype)

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__NUMBER__4`
- Urgency: `High`
