### ISSUE TITLE
[Event Page] 렌더링

### ISSUE THREAD

**Issue by code-kay** [codestates/story-hub-client#19]
### ISSUE
- Group:  `client`
- Type:`feature`
- Detail: Event Page 렌더링

### TODO
1. [ ] 파트 나누어서 렌더하기
2. [ ] 뭐 넣을지 고민해서 작성해보기
3. [ ] class, id 작성해서 CSS 작업하기

### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `Middle`
