### ISSUE TITLE
[Story Card] 렌더링

### ISSUE THREAD

**Issue by code-kay** [codestates/story-hub-client#28]
### ISSUE
- Group:  `client`
- Type:`feature`
- Detail: Story Card 렌더링

### TODO
1. [ ] 파트 나누어 렌더링하기
2. [ ] 버튼, 텍스트, 뷰 작성하기
3. [ ] class, id 작성해서 CSS 작업하기

### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `Middle`
