### ISSUE TITLE
[Client] 개발환경 세팅

### ISSUE THREAD

**Issue by code-kay** [codestates/story-hub-client#61]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 개발 환경 세팅

### TODO
1. [x] Package.json 작성
2. [x] create react app 이후 큰 틀 잡기
3. [x] 기본적인 라우팅 해주기

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint 2`
- Urgency: `Middle`
