### ISSUE TITLE
[Board Page] 렌더링

### ISSUE THREAD

**Issue by code-kay** [codestates/story-hub-client#8]
### ISSUE
- Group:  `client`
- Type:`feature`
- Detail: Board Page 렌더링

### TODO
1. [ ] Story 카드 렌더하기
2. [ ] 페이지 버튼 만들기
3. [ ]  class, id 작성해서 CSS 작업하기

### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `Middle`
